### ISSUE TITLE
Score Deletion

### ISSUE THREAD

**Issue by spcmky** [spcmky/cssr#17]
Scores must be able to be edited AND deleted once entered. Currently they can be changed but not removed. This feature is critical.

**Comment by melissactran** [comment]
Staff must be able to remove scores altogether in the event of schedule changes, mistakes and other unexpected events.

Currently, once a staff enters a score, they can edit the score but not remove it altogether.

When they select "N/A" to try to remove a score they receive a message saying they must enter a score.

**Comment by htran888** [comment]
Not complete

**Comment by spcmky** [comment]
Completed.

**Comment by melissactran** [comment]
Validated- complete
