### ISSUE TITLE
The "Student Record" Report is not functioning properly. 

### ISSUE THREAD

**Issue by spcmky** [spcmky/cssr#21]
The "Student Record" Report is not functioning properly. That report is supposed to accomplish the following:
* Allow user to see and select from all students assigned to a staff case load by choosing a staff member's name. - working
* Allow user to check one or more students' boxes to run a report. - working
* The actual report is supposed to show the entire history- all scores and comments from all areas for the students selected and also give each student's average score- NOT working. Currently this report is only showing the scores and comments from the case load selected.

Clarification - the student record report is only showing the scores and comments that were entered by the staff member whose caseload is selected by the user. The report needs to show all scores and comments the selected students received from ALL staff/areas to which they were assigned.

**Comment by melissactran** [comment]
Complete
