### ISSUE TITLE
Can't add dormitories

### ISSUE THREAD

**Issue by melissactran** [spcmky/cssr#22]
Error message appears after hitting "save" when attempting to add a dormitory under "Center Setup"

**Comment by spcmky** [comment]
This should be fixed.

**Comment by htran888** [comment]
Now I just see a big white screen when I hit save and changes are not saved

**Comment by spcmky** [comment]
I cannot replicate this.  Perhaps you are leaving a blank item before saving.  There is no validation in place and it will try and add an empty dorm or vocation which will result in an error.

**Comment by melissactran** [comment]
Ok, I see what you mean and I deleted the extra box at the bottom and was then able to add another dorm. But neither the client nor I were able to figure that out without your prompt. So can you make that functionality more transparent/ have a pop-up explanation/instruction?

**Comment by melissactran** [comment]
Chris,

I know you weren't able to load the updates you made last week due to an
access problem, but have you made those changes now? I have to give the
client and update tomorrow and want to report up to date progress but don't
see any noted.

Please let me know.

Thanks,

Melissa

**Comment by melissactran** [comment]
Hey Chris,

Thanks for making those fixes. They are making a difference to the users
and have been noticed. Can you please give me an idea on where we are with
the outstanding items? I have to report on progress weekly.

Thanks,

Melissa
