### ISSUE TITLE
On the View Scores Colums, the "Total" and "Units" colums are not always accurate; therefore the average is wrong.

### ISSUE THREAD

**Issue by melissactran** [spcmky/cssr#23]
Example from this week: 
Woodstock #21 on the View Scores Report is Jasmine A Ball 
She was scored in 4 areas but the "Units" column counts "5"
The sum of her scores is 12 but the "Total" column indicates "16"

This has been reported as a concern by other centers as well but I can't find a pattern or determine why it only happens sometimes.

**Comment by spcmky** [comment]
I believe the issue is that on slow connections its possible to create multiple score entries.  The submit button becomes disabled until the request is finished now.

**Comment by htran888** [comment]
ongoing monitoring needed

**Comment by melissactran** [comment]
So far, so good. Continuing to monitor
