### ISSUE TITLE
Indy "Create student" is not functioning

### ISSUE THREAD

**Issue by melissactran** [spcmky/cssr#25]
Under User setup/ Student/ Add student, Nothing happens when the fields are completed and you select "Create student". This center can't add new students.

**Comment by spcmky** [comment]
Looks like it's because there isn't any dorm available or selected.  Can you confirm this?

**Comment by melissactran** [comment]
I just tested this and it works fine now that I added "non-res" as a dorm

**Comment by melissactran** [comment]
You can close this.
